---
- name: Installing nop commerce
  hosts: all
  become: yes
  tasks:
    - name: update apt repo and cache
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: install apache2
      package:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: install openjdk 11
      package:
        name: "{{ java_package }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: installing PHP
      package:
        name: 
          - php 
          - libapache2-mod-php
          - php-mysql
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: firewall setting
      community.general.ufw:
        name: apache
        state: enable
      when: ansible_facts['os_family'] == "Debian"


