---
- name: Installing nop commerce
  hosts: all
  become: yes
  vars:
    - java_package:  openjdk-11-jdk
    - domain_name: mydevops
    - username: 'devops'
  tasks:
    - name: update apt repo and cache
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: install apache2
      package:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: installing PHP
      package:
        name: 
          - php 
          - libapache2-mod-php
          - php-mysql
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: firewall setting
      community.general.ufw:
        name: apache
        state: enabled
      when: ansible_facts['os_family'] == "Debian"
    - name: installing mysql 
      package:
        name: mysql-server
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: creating directory for domain
      ansible.builtin.file:
        path: /var/www/{{ domain_name }}
        state: directory
      when: ansible_facts['os_family'] == "Debian"
    - name: assign ownership to domain directory
      ansible.builtin.file:
        path: /var/www/{{ domain_name }}
        owner: "{{ username }}"
        recurse: yes
        state: directory
      when: ansible_facts['os_family'] == "Debian"
    - name: create the configuration file
      ansible.builtin.template:
        dest: /etc/apache2/sites-available/mydevops.conf
        src: 'mydevops.conf.j2'
        owner: "{{ username }}"
        group: "{{ username }}"
      when: ansible_facts['os_family'] == "Debian"






